version: '3'

services:
  prometheus:
    image: prom/prometheus:v2.23.0
    container_name: prom
    volumes:
      - "$PWD/prom/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "$PWD/prom/prometheus/:/prometheus/"
      - "$PWD/prom/conf.d/:/etc/prometheus/conf.d/"
    restart: always
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention=90d'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--storage.tsdb.max-block-duration=7d'
      - '--web.enable-lifecycle'

  grafana:
    image: grafana/grafana:7.3.6
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - $PWD/grafana:/var/lib/grafana
      - $PWD/grafana/etc:/etc/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always

  node_exporter:
    privileged: true
    image: prom/node-exporter:v1.0.1
    container_name: node-exporter
    restart: always
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points"
      - "^/(rootfs/)?(dev|etc|host|proc|run|sys|volume1)($$|/)"

  blackbox_exporter:
    image: prom/blackbox-exporter:v0.18.0
    container_name: blackbox
    restart: always
    ports:
      - "9115:9115"
    volumes:
      - "$PWD/blackbox:/config"
    command: --config.file=/config/blackbox.yml

  snmp-exporter:
    image: prom/snmp-exporter:v0.19.0
    container_name: snmp-exporter
    volumes:
      - $PWD/snmp/snmp.yml:/etc/snmp_exporter/snmp.yml
    ports:
      - 9116:9116

  loki:
    image: grafana/loki:2.0.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.0.0
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml